### ISSUE TITLE
input element does not response to state change and hot reload?

### ISSUE THREAD

**Issue by free-kingdom** [fulcrologic/fulcro#568]
in version `com.fulcrologic/fulcro {:mvn/version "3.9.0-rc2"}`

for example, when state 'editing?' changes (can be observed in fulcro inspect), the class dose not change,

```clojure
(dom/input
  {:classes ["font-bold text-xl" "rounded-lg"
             (when editing?
               (if (fs/dirty? props :user/name)
                 "border border-red-700"
                 "border border-yellow-950/40"))]
   :value name
   :onChange (fn [evt]
               (m/set-value! this :user/name (evt/target-value evt)))})
```

no problem in other elements.

**Comment by awkay** [comment]
Ah, that was the main porting issue to react 19: they messed with the published APIs that this relied on and I had to rewrite it. I didn't support the :classes option

**Comment by free-kingdom** [comment]
> Ah, that was the main porting issue to react 19: they messed with the published APIs that this relied on and I had to rewrite it. I didn't support the :classes option. So yes, bug.

Other options like :readOnly also don't work. In `com.fulcrologic.fulcro.dom/wrap-form-element,` the entire props is cached in a react state, which seems to be the cause of the issue？

**Comment by awkay** [comment]
Yes, I've started a patch. I've got all of your issues fixed, but it broke the cursor jump fix, which was the whole point...so still hacking on it.

**Comment by awkay** [comment]
Fixed in rc3

**Comment by free-kingdom** [comment]
> Fixed in rc3

Still buggy. I separated the `useEffect` into two, and it works for my case now. The `cond` form in the original code short-circuits the `props-changed?` update?

```clojure
(defn wrap-form-element [input-type]
  (let [element (fn [^js props]
                  (let [internal-ref      (react/useRef nil)
                        checkbox?         (= "checkbox" (gobj/get props "type"))
                        value-field       (if checkbox? "checked" "value")
                        new-value         (gobj/get props value-field)
                        ref               (or (gobj/get props "ref") internal-ref)
                        pstate            (react/useState props)
                        cached-props      (aget pstate 0)
                        set-cached-props! (aget pstate 1)
                        node              (when ref (gobj/get ref "current"))
                        node-value        (when node (gobj/get node value-field))
                        ;; Check if non-value props have changed
                        props-changed?    (let [cached-clone (gobj/clone cached-props)
                                                props-clone  (gobj/clone props)]
                                            ;; Remove value fields for comparison
                                            (gobj/remove cached-clone value-field)
                                            (gobj/remove cached-clone "onChange")
                                            (gobj/remove cached-clone "ref")
                                            (gobj/remove props-clone value-field)
                                            (gobj/remove props-clone "onChange")
                                            (gobj/remove props-clone "ref")
                                            (not (gobj/equals cached-clone props-clone)))]
                    (react/useEffect
                      (fn []
                        (update-value! props value-field ref set-cached-props! new-value)
                        js/undefined)
                      #js [props-changed?])

                    (react/useEffect
                      (fn []
                        (cond
                          checkbox?
                          (update-value! props value-field ref set-cached-props! new-value)

                          (and (some? node-value) (= new-value node-value))
                          nil

                          (and (some? node-value) (not= new-value node-value))
                          (update-value! props value-field ref set-cached-props! node-value)

                          (nil? node-value)
                          (update-value! props value-field ref set-cached-props! new-value))
                        js/undefined)
                      #js [new-value])
                    (create-element input-type cached-props)))]
    (fn [^js props]
      (create-element element props))))
```

**Comment by awkay** [comment]
rc4
